@PersonApi_HostAddress = https://localhost:7084

GET {{PersonApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{PersonApi_HostAddress}}/api/persondetails
Content-Type: application/json

{
  "name" : "Jack Micheal",
  "Phone": "7806801122",
  "Email": "jackmicheal@email.com",
  "Address": "1234 12a ave NW, Edmonton",
  "PostalZip": "T0T 1R1",
  "Region": "AB",
  "Country": "Canada"
}

###

@id=1
PUT {{PersonApi_HostAddress}}/api/persondetails/{{id}}
Content-Type: application/json

{
    "PersonId": "1",
    "Name": "john Doe",
    "Phone": "7801234567",
    "Email": "JohnDoe#macewan.ca",
    "Address": "9876 54 St SW, Edmonton",
    "PostalZip": "T7T 9R9",
    "Region": "AB",
    "Country": "Canada"
}

###

GET {{PersonApi_HostAddress}}/api/persondetails/{{id}}

###

DELETE {{PersonApi_HostAddress}}/api/persondetails/{{id}}

###
